# Generated by Django 3.0 on 2021-12-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='countryName',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
