# Generated by Django 3.0 on 2021-12-09 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
    ]
